# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'myregistry011623'
    repository: 'image'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'manifests'
    publishLocation: 'pipeline'

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'devops-service-connection'
    namespace: 'default'
    command: 'get'
    arguments: 'pods'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'MCAPS-Hybrid-REQ-49139-2022-cindywang(d6ce0703-8dc9-4787-9429-452311475d64)'
    azureContainerRegistry: 'myregistry011623.azurecr.io'
    secretName: 'devops-secret'